Adding base code for brightness and color changes.
pogi7/luminosityleds pull request #21
Opened 2022-12-04 03:25 UTC by WhenitStarted

# Description

have the mcu read the current brightness and color of the led strip

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Testing Color and brightness change
- [ ] Test B

# Checklist (when relevant):

- [X] My code follows the style guidelines of this project

    [TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [ ] I have included a reviewer on the pull request [@pogi7 @aematei ]
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-09 01:39 UTC, aematei commented
Looks like we had some similar issues with our commits (LL-27 for me). I'll post some of the comments Aaron had for me here:

>"Your code is failing the python linter.

Make sure the linter passes locally.

python3 -m venv venv
pip install pylint
pylint --rcfile=./controller/pylintrc $(git ls-files '*.py')"

2023-01-09 01:44 UTC, aematei commented
Let me know if you wanna meet up some time this week to go over merging our work, we can also discuss more style topics, if you'd like.

2023-01-19 22:32 UTC, aematei requested changes

2023-01-19 22:32 UTC, aematei commented on controller/lights.py
> +    def setConnected(self, connect):
You can remove connected stuff from this module, it'll be in wlan.py.

2023-01-19 22:32 UTC, aematei commented on controller/lights.py
> +    def __init__(self, pin, pixelNums):
Type hinting

2023-01-19 22:37 UTC, aematei commented on controller/lights.py
> +        self._pin = machine.Pin(pin, Pin.OUT)
Just refer to machine.Pin as Pin, because you used `from machine import Pin` in line 1.

2023-01-19 22:38 UTC, aematei commented on controller/lights.py
> +        self._neopixel = neopixel.NeoPixel(self._pin, self._pixelCount)
Just put this below any variable declarations used in this line.

2023-01-27 09:24 UTC, pogi7 commented on controller/Archived/LightControls.py
> +    # def setBrightness(self, brightness):
why is this commented out?

2023-01-27 09:34 UTC, pogi7 requested changes
@WhenitStarted I don't understand why you have an `Archived` directory.

I would talk with @aematei to make sure the `controller` directory structure matches.

2023-01-28 04:50 UTC, pogi7 approved these changes
lgtm

2023-01-28 04:50 UTC, merged