LL-96
pogi7/luminosityleds pull request #43
Opened 2023-01-14 05:38 UTC by vliu36

# Description

Please include a summary of the change and its subsequent issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Subsequent # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

1. Get client id and secret from Vinson 
2. Use a .env file or replace id and secret variables with the respective client id and secret (DO NOT PUSH TO GITHUB)

Client:
1. ``` cd client ```
2. ``` npm start ```
3. Click login/register buttons and follow the prompts
4. Check server console

Server:
1. Run ``` src/routes/github.ts ```

# Checklist (when relevant):

- [ ] My code follows the style guidelines of this project

    [TypeScript](https://google.github.io/styleguide/tsguide.html)
[Python](https://peps.python.org/pep-0008/)
[Schema](https://learn.microsoft.com/en-us/previous-versions/windows/desktop/forefront-2010/ee652242(v=vs.100))
- [ ] I have included a reviewer on the pull request [*Replace this text with the reviewer*]
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-14 07:02 UTC, pogi7 commented on client/src/components/ThirdParty.tsx
> +  const CLIENT_ID = process.env.GITHUB_CLIENT_ID;
To get `environment variables` in React to work follow this guide:
https://stackoverflow.com/questions/49108136/importing-env-variable-react-front-end

2023-01-14 07:02 UTC, pogi7 commented on server/src/routes/githubTest.ts
> +
import this into `server/server.ts` file

2023-01-14 07:03 UTC, pogi7 commented on server/src/routes/githubTest.ts
> +app.get('/github', (req: Request, res: Response) => {
Use the express.router module.  Look at `server/routes/routes.ts` page.  Call the path with an `axios` call in the client end

2023-01-18 05:28 UTC, pogi7 requested changes
I can't merge this until the pipeline passes:
https://github.com/pogi7/luminosityleds/actions/runs/3946000651/jobs/6753378078

2023-01-20 07:16 UTC, erikajledesma requested changes
@vliu36 Just tested your code, not sure why I get the following error on the console: 
![image](https://user-images.githubusercontent.com/44066676/213638404-d633747f-1f42-4761-a1b3-44f807ab9be9.png)

2023-03-12 02:48 UTC, pogi7 commented
@vliu36 Please fix the merge conflicts.  Let me know if you have any questions.

2023-04-23 22:38 UTC, Verus20 approved these changes
LGTM!

2023-04-23 23:56 UTC, pogi7 approved these changes
Lgtm

2023-04-23 23:56 UTC, merged